//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class ClaimSubmitResult {
    
    private SubmitError[] documentLevelErrorsField;
    
    private SubmitResult[] claimResultsField;
    
    /// <remarks/>
    public SubmitError[] DocumentLevelErrors {
        get {
            return this.documentLevelErrorsField;
        }
        set {
            this.documentLevelErrorsField = value;
        }
    }
    
    /// <remarks/>
    public SubmitResult[] ClaimResults {
        get {
            return this.claimResultsField;
        }
        set {
            this.claimResultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SubmitError {
    
    private SubmitErrorType typeField;
    
    private string codeField;
    
    private string locationField;
    
    private string supplementalInformationField;
    
    /// <remarks/>
    public SubmitErrorType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public string SupplementalInformation {
        get {
            return this.supplementalInformationField;
        }
        set {
            this.supplementalInformationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
public enum SubmitErrorType {
    
    /// <remarks/>
    Unknown,
    
    /// <remarks/>
    Syntax,
    
    /// <remarks/>
    Validation,
    
    /// <remarks/>
    System,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SubmitResult {
    
    private string vendorClaimIdField;
    
    private SubmitStatus statusField;
    
    private SubmitError[] errorsField;
    
    private string requestIdField;
    
    /// <remarks/>
    public string VendorClaimId {
        get {
            return this.vendorClaimIdField;
        }
        set {
            this.vendorClaimIdField = value;
        }
    }
    
    /// <remarks/>
    public SubmitStatus Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public SubmitError[] Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    public string RequestId {
        get {
            return this.requestIdField;
        }
        set {
            this.requestIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
public enum SubmitStatus {
    
    /// <remarks/>
    Unknown,
    
    /// <remarks/>
    Accepted,
    
    /// <remarks/>
    NotAccepted,
}
