//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class Payer {
    
    private PayerType typeField;
    
    private string nameField;
    
    private string apexPayerIdField;
    
    private string nationalPayerIdField;
    
    private ERAAvailability eraAvailabilityField;
    
    private bool offersEligibilityField;
    
    private bool claimEnrollmentRequiredField;
    
    /// <remarks/>
    public PayerType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string ApexPayerId {
        get {
            return this.apexPayerIdField;
        }
        set {
            this.apexPayerIdField = value;
        }
    }
    
    /// <remarks/>
    public string NationalPayerId {
        get {
            return this.nationalPayerIdField;
        }
        set {
            this.nationalPayerIdField = value;
        }
    }
    
    /// <remarks/>
    public ERAAvailability EraAvailability {
        get {
            return this.eraAvailabilityField;
        }
        set {
            this.eraAvailabilityField = value;
        }
    }
    
    /// <remarks/>
    public bool OffersEligibility {
        get {
            return this.offersEligibilityField;
        }
        set {
            this.offersEligibilityField = value;
        }
    }
    
    /// <remarks/>
    public bool ClaimEnrollmentRequired {
        get {
            return this.claimEnrollmentRequiredField;
        }
        set {
            this.claimEnrollmentRequiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
public enum PayerType {
    
    /// <remarks/>
    Unknown,
    
    /// <remarks/>
    Dental,
    
    /// <remarks/>
    Medical,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
public enum ERAAvailability {
    
    /// <remarks/>
    NotAvailable,
    
    /// <remarks/>
    Available,
    
    /// <remarks/>
    RequiresEnrollment,
}
