//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class MedicalClaimsJson {
    
    private string documentTypeField;
    
    private MedicalClaimJson[] claimsField;
    
    /// <remarks/>
    public string DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    public MedicalClaimJson[] Claims {
        get {
            return this.claimsField;
        }
        set {
            this.claimsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MedicalClaimJson {
    
    private string apex_PayerIdField;
    
    private string apex_VendorClaimIdField;
    
    private string f00_PayerNameField;
    
    private string f00_PayerAddress1Field;
    
    private string f00_PayerAddress2Field;
    
    private string f00_PayerCityField;
    
    private string f00_PayerStateField;
    
    private string f00_PayerZipField;
    
    private string f01_ClaimTypeField;
    
    private string f01A_InsuredIdField;
    
    private string f02_PatientNameLastField;
    
    private string f02_PatientNameFirstField;
    
    private string f02_PatientNameMiddleField;
    
    private string f02_PatientSuffixField;
    
    private string f03_PatientDobField;
    
    private string f03_PatientSexField;
    
    private string f04_InsuredNameLastField;
    
    private string f04_InsuredNameFirstField;
    
    private string f04_InsuredNameMiddleField;
    
    private string f04_InsuredSuffixField;
    
    private string f05_PatientAddress1Field;
    
    private string f05_PatientAddress2Field;
    
    private string f05_PatientCityField;
    
    private string f05_PatientStateField;
    
    private string f05_PatientZipField;
    
    private string f05_PatientPhoneField;
    
    private string f06_PatientRelationshipToInsuredField;
    
    private string f07_InsuredAddress1Field;
    
    private string f07_InsuredAddress2Field;
    
    private string f07_InsuredCityField;
    
    private string f07_InsuredStateField;
    
    private string f07_InsuredZipField;
    
    private string f07_InsuredPhoneField;
    
    private string f09_OtherInsuredNameLastField;
    
    private string f09_OtherInsuredNameFirstField;
    
    private string f09_OtherInsuredNameMiddleField;
    
    private string f09_OtherInsuredSuffixField;
    
    private string f09A_OtherInsuredGroupNumField;
    
    private string f09B_OtherInsuredDOBField;
    
    private string f09B_OtherInsuredSexField;
    
    private string f09C_OtherEmployerNameField;
    
    private string f09_PatientRelationshipToInsuredField;
    
    private string f09D_OtherPlanNameField;
    
    private bool f10A_PatientCondEmploymentField;
    
    private bool f10B_PatientCondAutoAccidentField;
    
    private string f10B_PatientCondAutoAccidentStateField;
    
    private bool f10C_PatientCondOtherAccidentField;
    
    private string[] f10D_ClaimCodesField;
    
    private string f11_InsuredsPolicyGroupOrFecaNumberField;
    
    private string f11A_InsuredDobField;
    
    private string f11A_InsuredSexField;
    
    private string f11B_OtherClaimIdSsnField;
    
    private string f11C_PlanNameField;
    
    private bool f11D_OtherPlanField;
    
    private string f12_PatientAuthorizationField;
    
    private string f12_PatientAuthorizationDateField;
    
    private string f13_InsuredAuthorizationField;
    
    private string f14_DateOfCurrentIllnessOrSymptomField;
    
    private string f14_LastMenstrualPeriodDateField;
    
    private string f15_InitialTreatmentDateField;
    
    private string f15_LastSeenDateField;
    
    private string f15_AcuteManifestionDateField;
    
    private string f15_AccidentDateField;
    
    private string f15_LastXRayDateField;
    
    private string f15_HearingAndVisionPrescriptionDateField;
    
    private string f15_AssumedCareStartDateField;
    
    private string f15_AssumedCareEndDateField;
    
    private string f15_PropertyCasualtyFirstContactDateField;
    
    private string f16_LastWorkedDateField;
    
    private string f16_AuthorizedReturnToWorkDateField;
    
    private string f17_ReferringProviderNameLastField;
    
    private string f17_ReferringProviderNameFirstField;
    
    private string f17_ReferringProviderNameMiddleField;
    
    private string f17_ReferringProviderSuffixField;
    
    private string f17_SupervisingProviderNameLastField;
    
    private string f17_SupervisingProviderNameFirstField;
    
    private string f17_SupervisingProviderNameMiddleField;
    
    private string f17_SupervisingProviderSuffixField;
    
    private string f17_OrderingProviderNameLastField;
    
    private string f17_OrderingProviderNameFirstField;
    
    private string f17_OrderingProviderNameMiddleField;
    
    private string f17_OrderingProviderSuffixField;
    
    private string f17A_ReferringProviderIdNumberField;
    
    private string f17A_SupervisingProviderIdNumberField;
    
    private string f17A_OrderingProviderIdNumberField;
    
    private string f17B_ReferringProviderNpiField;
    
    private string f17B_SupervisingProviderNpiField;
    
    private string f17B_OrderingProviderNpiField;
    
    private string f18_HospitalizationDateFromField;
    
    private string f18_HospitalizationDateToField;
    
    private string f19_ClaimSupplementalInfoNoteTextField;
    
    private string f21_IcdIndicatorField;
    
    private string[] f21_DiagnosisCodesField;
    
    private string f22_MedicaidResubmissionCodeField;
    
    private string f22_OriginalReferenceNumberField;
    
    private string f23_PriorAuthorizationNumberField;
    
    private string f23_ReferralNumberField;
    
    private string f23_ClinicalLaboratoryImprovementAmendmentNumberField;
    
    private string f23_MammographyCertificationNumberField;
    
    private F24ClaimLines[] f24_ClaimLinesField;
    
    private string f25_FederalTaxIdEinField;
    
    private string f25_FederalTaxIdSsnField;
    
    private string f26_PatientAcctNumberField;
    
    private string f27_AcceptAssignmentField;
    
    private decimal f28_TotalChargeField;
    
    private System.Nullable<decimal> f29_PatientAmountPaidField;
    
    private System.Nullable<decimal> f29_PayerAmountPaidField;
    
    private bool f31_PhysicianOrSupplierSignatureIsOnFileField;
    
    private string f32_FacilityNameField;
    
    private string f32_FacilityAddress1Field;
    
    private string f32_FacilityAddress2Field;
    
    private string f32_FacilityCityField;
    
    private string f32_FacilityStateField;
    
    private string f32_FacilityZipField;
    
    private string f32A_FacilityNpiField;
    
    private string f32B_FacilityIdStateLicenseNumberField;
    
    private string f32B_FacilityIdProviderCommercialLicenseNumberField;
    
    private string f32B_FacilityIdLocationNumberField;
    
    private string f33_BillingProviderNameLastField;
    
    private string f33_BillingProviderNameFirstField;
    
    private string f33_BillingProviderNameMiddleField;
    
    private string f33_BillingProviderSuffixField;
    
    private string f33_BillingProviderAddress1Field;
    
    private string f33_BillingProviderAddress2Field;
    
    private string f33_BillingProviderCityField;
    
    private string f33_BillingProviderStateField;
    
    private string f33_BillingProviderZipField;
    
    private string f33_BillingProviderPhoneNumberField;
    
    private string f33A_BillingProviderNpiField;
    
    private string f33B_BillingProviderTaxonomyCodeField;
    
    private string f33B_BillingProviderEmployersIdentificationNumberField;
    
    private string f33B_BillingProviderSsnField;
    
    private string x12_PlaceOfServiceCodeField;
    
    private string x12_RendProviderNameLastField;
    
    private string x12_RendProviderNameFirstField;
    
    private string x12_RendProviderNameMiddleField;
    
    private string x12_RendProviderSuffixField;
    
    private string x12_RendProviderTaxonomyCodeField;
    
    private string x12_RendProviderStateLicenseNumberField;
    
    private string x12_RendProviderUpinNumberField;
    
    private string x12_RendProviderCommercialNumberField;
    
    private string x12_RendProviderLocationNumberField;
    
    private string x12_RenderingNPIField;
    
    private string x12_AcuteManifestationCodeField;
    
    private string x12_ClaimAdjudicationDateField;
    
    private System.Nullable<decimal> x12_ClaimPrimaryPayerPaidAmountField;
    
    private ClaimsAdjustment[] x12_ClaimContractualObligationAdjustmentsField;
    
    private ClaimsAdjustment[] x12_ClaimCorrectionAndReversalAdjustmentsField;
    
    private ClaimsAdjustment[] x12_ClaimOtherAdjustmentsField;
    
    private ClaimsAdjustment[] x12_ClaimPayorInitiatedReductionsField;
    
    private ClaimsAdjustment[] x12_ClaimPatientResponsibilityAdjustmentsField;
    
    private string x12_MedicalRecordNumberField;
    
    private PatientConditionInfo[] x12_SpectacleLensesField;
    
    private PatientConditionInfo[] x12_ContactLensesField;
    
    private PatientConditionInfo[] x12_SpectacleFramesField;
    
    private string x12_DisabilityDateFromField;
    
    private string x12_DisabilityDateToField;
    
    private System.Nullable<decimal> x12_ClaimContractMonetaryAmountField;
    
    private string x12_ClaimContractTypeCodeField;
    
    private string x12_ClaimContractCodeField;
    
    private string x12_DelayReasonCodeField;
    
    private string x12_OtherPayerNameField;
    
    /// <remarks/>
    public string Apex_PayerId {
        get {
            return this.apex_PayerIdField;
        }
        set {
            this.apex_PayerIdField = value;
        }
    }
    
    /// <remarks/>
    public string Apex_VendorClaimId {
        get {
            return this.apex_VendorClaimIdField;
        }
        set {
            this.apex_VendorClaimIdField = value;
        }
    }
    
    /// <remarks/>
    public string F00_PayerName {
        get {
            return this.f00_PayerNameField;
        }
        set {
            this.f00_PayerNameField = value;
        }
    }
    
    /// <remarks/>
    public string F00_PayerAddress1 {
        get {
            return this.f00_PayerAddress1Field;
        }
        set {
            this.f00_PayerAddress1Field = value;
        }
    }
    
    /// <remarks/>
    public string F00_PayerAddress2 {
        get {
            return this.f00_PayerAddress2Field;
        }
        set {
            this.f00_PayerAddress2Field = value;
        }
    }
    
    /// <remarks/>
    public string F00_PayerCity {
        get {
            return this.f00_PayerCityField;
        }
        set {
            this.f00_PayerCityField = value;
        }
    }
    
    /// <remarks/>
    public string F00_PayerState {
        get {
            return this.f00_PayerStateField;
        }
        set {
            this.f00_PayerStateField = value;
        }
    }
    
    /// <remarks/>
    public string F00_PayerZip {
        get {
            return this.f00_PayerZipField;
        }
        set {
            this.f00_PayerZipField = value;
        }
    }
    
    /// <remarks/>
    public string F01_ClaimType {
        get {
            return this.f01_ClaimTypeField;
        }
        set {
            this.f01_ClaimTypeField = value;
        }
    }
    
    /// <remarks/>
    public string F01A_InsuredId {
        get {
            return this.f01A_InsuredIdField;
        }
        set {
            this.f01A_InsuredIdField = value;
        }
    }
    
    /// <remarks/>
    public string F02_PatientNameLast {
        get {
            return this.f02_PatientNameLastField;
        }
        set {
            this.f02_PatientNameLastField = value;
        }
    }
    
    /// <remarks/>
    public string F02_PatientNameFirst {
        get {
            return this.f02_PatientNameFirstField;
        }
        set {
            this.f02_PatientNameFirstField = value;
        }
    }
    
    /// <remarks/>
    public string F02_PatientNameMiddle {
        get {
            return this.f02_PatientNameMiddleField;
        }
        set {
            this.f02_PatientNameMiddleField = value;
        }
    }
    
    /// <remarks/>
    public string F02_PatientSuffix {
        get {
            return this.f02_PatientSuffixField;
        }
        set {
            this.f02_PatientSuffixField = value;
        }
    }
    
    /// <remarks/>
    public string F03_PatientDob {
        get {
            return this.f03_PatientDobField;
        }
        set {
            this.f03_PatientDobField = value;
        }
    }
    
    /// <remarks/>
    public string F03_PatientSex {
        get {
            return this.f03_PatientSexField;
        }
        set {
            this.f03_PatientSexField = value;
        }
    }
    
    /// <remarks/>
    public string F04_InsuredNameLast {
        get {
            return this.f04_InsuredNameLastField;
        }
        set {
            this.f04_InsuredNameLastField = value;
        }
    }
    
    /// <remarks/>
    public string F04_InsuredNameFirst {
        get {
            return this.f04_InsuredNameFirstField;
        }
        set {
            this.f04_InsuredNameFirstField = value;
        }
    }
    
    /// <remarks/>
    public string F04_InsuredNameMiddle {
        get {
            return this.f04_InsuredNameMiddleField;
        }
        set {
            this.f04_InsuredNameMiddleField = value;
        }
    }
    
    /// <remarks/>
    public string F04_InsuredSuffix {
        get {
            return this.f04_InsuredSuffixField;
        }
        set {
            this.f04_InsuredSuffixField = value;
        }
    }
    
    /// <remarks/>
    public string F05_PatientAddress1 {
        get {
            return this.f05_PatientAddress1Field;
        }
        set {
            this.f05_PatientAddress1Field = value;
        }
    }
    
    /// <remarks/>
    public string F05_PatientAddress2 {
        get {
            return this.f05_PatientAddress2Field;
        }
        set {
            this.f05_PatientAddress2Field = value;
        }
    }
    
    /// <remarks/>
    public string F05_PatientCity {
        get {
            return this.f05_PatientCityField;
        }
        set {
            this.f05_PatientCityField = value;
        }
    }
    
    /// <remarks/>
    public string F05_PatientState {
        get {
            return this.f05_PatientStateField;
        }
        set {
            this.f05_PatientStateField = value;
        }
    }
    
    /// <remarks/>
    public string F05_PatientZip {
        get {
            return this.f05_PatientZipField;
        }
        set {
            this.f05_PatientZipField = value;
        }
    }
    
    /// <remarks/>
    public string F05_PatientPhone {
        get {
            return this.f05_PatientPhoneField;
        }
        set {
            this.f05_PatientPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string F06_PatientRelationshipToInsured {
        get {
            return this.f06_PatientRelationshipToInsuredField;
        }
        set {
            this.f06_PatientRelationshipToInsuredField = value;
        }
    }
    
    /// <remarks/>
    public string F07_InsuredAddress1 {
        get {
            return this.f07_InsuredAddress1Field;
        }
        set {
            this.f07_InsuredAddress1Field = value;
        }
    }
    
    /// <remarks/>
    public string F07_InsuredAddress2 {
        get {
            return this.f07_InsuredAddress2Field;
        }
        set {
            this.f07_InsuredAddress2Field = value;
        }
    }
    
    /// <remarks/>
    public string F07_InsuredCity {
        get {
            return this.f07_InsuredCityField;
        }
        set {
            this.f07_InsuredCityField = value;
        }
    }
    
    /// <remarks/>
    public string F07_InsuredState {
        get {
            return this.f07_InsuredStateField;
        }
        set {
            this.f07_InsuredStateField = value;
        }
    }
    
    /// <remarks/>
    public string F07_InsuredZip {
        get {
            return this.f07_InsuredZipField;
        }
        set {
            this.f07_InsuredZipField = value;
        }
    }
    
    /// <remarks/>
    public string F07_InsuredPhone {
        get {
            return this.f07_InsuredPhoneField;
        }
        set {
            this.f07_InsuredPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string F09_OtherInsuredNameLast {
        get {
            return this.f09_OtherInsuredNameLastField;
        }
        set {
            this.f09_OtherInsuredNameLastField = value;
        }
    }
    
    /// <remarks/>
    public string F09_OtherInsuredNameFirst {
        get {
            return this.f09_OtherInsuredNameFirstField;
        }
        set {
            this.f09_OtherInsuredNameFirstField = value;
        }
    }
    
    /// <remarks/>
    public string F09_OtherInsuredNameMiddle {
        get {
            return this.f09_OtherInsuredNameMiddleField;
        }
        set {
            this.f09_OtherInsuredNameMiddleField = value;
        }
    }
    
    /// <remarks/>
    public string F09_OtherInsuredSuffix {
        get {
            return this.f09_OtherInsuredSuffixField;
        }
        set {
            this.f09_OtherInsuredSuffixField = value;
        }
    }
    
    /// <remarks/>
    public string F09A_OtherInsuredGroupNum {
        get {
            return this.f09A_OtherInsuredGroupNumField;
        }
        set {
            this.f09A_OtherInsuredGroupNumField = value;
        }
    }
    
    /// <remarks/>
    public string F09B_OtherInsuredDOB {
        get {
            return this.f09B_OtherInsuredDOBField;
        }
        set {
            this.f09B_OtherInsuredDOBField = value;
        }
    }
    
    /// <remarks/>
    public string F09B_OtherInsuredSex {
        get {
            return this.f09B_OtherInsuredSexField;
        }
        set {
            this.f09B_OtherInsuredSexField = value;
        }
    }
    
    /// <remarks/>
    public string F09C_OtherEmployerName {
        get {
            return this.f09C_OtherEmployerNameField;
        }
        set {
            this.f09C_OtherEmployerNameField = value;
        }
    }
    
    /// <remarks/>
    public string F09_PatientRelationshipToInsured {
        get {
            return this.f09_PatientRelationshipToInsuredField;
        }
        set {
            this.f09_PatientRelationshipToInsuredField = value;
        }
    }
    
    /// <remarks/>
    public string F09D_OtherPlanName {
        get {
            return this.f09D_OtherPlanNameField;
        }
        set {
            this.f09D_OtherPlanNameField = value;
        }
    }
    
    /// <remarks/>
    public bool F10A_PatientCondEmployment {
        get {
            return this.f10A_PatientCondEmploymentField;
        }
        set {
            this.f10A_PatientCondEmploymentField = value;
        }
    }
    
    /// <remarks/>
    public bool F10B_PatientCondAutoAccident {
        get {
            return this.f10B_PatientCondAutoAccidentField;
        }
        set {
            this.f10B_PatientCondAutoAccidentField = value;
        }
    }
    
    /// <remarks/>
    public string F10B_PatientCondAutoAccidentState {
        get {
            return this.f10B_PatientCondAutoAccidentStateField;
        }
        set {
            this.f10B_PatientCondAutoAccidentStateField = value;
        }
    }
    
    /// <remarks/>
    public bool F10C_PatientCondOtherAccident {
        get {
            return this.f10C_PatientCondOtherAccidentField;
        }
        set {
            this.f10C_PatientCondOtherAccidentField = value;
        }
    }
    
    /// <remarks/>
    public string[] F10D_ClaimCodes {
        get {
            return this.f10D_ClaimCodesField;
        }
        set {
            this.f10D_ClaimCodesField = value;
        }
    }
    
    /// <remarks/>
    public string F11_InsuredsPolicyGroupOrFecaNumber {
        get {
            return this.f11_InsuredsPolicyGroupOrFecaNumberField;
        }
        set {
            this.f11_InsuredsPolicyGroupOrFecaNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F11A_InsuredDob {
        get {
            return this.f11A_InsuredDobField;
        }
        set {
            this.f11A_InsuredDobField = value;
        }
    }
    
    /// <remarks/>
    public string F11A_InsuredSex {
        get {
            return this.f11A_InsuredSexField;
        }
        set {
            this.f11A_InsuredSexField = value;
        }
    }
    
    /// <remarks/>
    public string F11B_OtherClaimIdSsn {
        get {
            return this.f11B_OtherClaimIdSsnField;
        }
        set {
            this.f11B_OtherClaimIdSsnField = value;
        }
    }
    
    /// <remarks/>
    public string F11C_PlanName {
        get {
            return this.f11C_PlanNameField;
        }
        set {
            this.f11C_PlanNameField = value;
        }
    }
    
    /// <remarks/>
    public bool F11D_OtherPlan {
        get {
            return this.f11D_OtherPlanField;
        }
        set {
            this.f11D_OtherPlanField = value;
        }
    }
    
    /// <remarks/>
    public string F12_PatientAuthorization {
        get {
            return this.f12_PatientAuthorizationField;
        }
        set {
            this.f12_PatientAuthorizationField = value;
        }
    }
    
    /// <remarks/>
    public string F12_PatientAuthorizationDate {
        get {
            return this.f12_PatientAuthorizationDateField;
        }
        set {
            this.f12_PatientAuthorizationDateField = value;
        }
    }
    
    /// <remarks/>
    public string F13_InsuredAuthorization {
        get {
            return this.f13_InsuredAuthorizationField;
        }
        set {
            this.f13_InsuredAuthorizationField = value;
        }
    }
    
    /// <remarks/>
    public string F14_DateOfCurrentIllnessOrSymptom {
        get {
            return this.f14_DateOfCurrentIllnessOrSymptomField;
        }
        set {
            this.f14_DateOfCurrentIllnessOrSymptomField = value;
        }
    }
    
    /// <remarks/>
    public string F14_LastMenstrualPeriodDate {
        get {
            return this.f14_LastMenstrualPeriodDateField;
        }
        set {
            this.f14_LastMenstrualPeriodDateField = value;
        }
    }
    
    /// <remarks/>
    public string F15_InitialTreatmentDate {
        get {
            return this.f15_InitialTreatmentDateField;
        }
        set {
            this.f15_InitialTreatmentDateField = value;
        }
    }
    
    /// <remarks/>
    public string F15_LastSeenDate {
        get {
            return this.f15_LastSeenDateField;
        }
        set {
            this.f15_LastSeenDateField = value;
        }
    }
    
    /// <remarks/>
    public string F15_AcuteManifestionDate {
        get {
            return this.f15_AcuteManifestionDateField;
        }
        set {
            this.f15_AcuteManifestionDateField = value;
        }
    }
    
    /// <remarks/>
    public string F15_AccidentDate {
        get {
            return this.f15_AccidentDateField;
        }
        set {
            this.f15_AccidentDateField = value;
        }
    }
    
    /// <remarks/>
    public string F15_LastXRayDate {
        get {
            return this.f15_LastXRayDateField;
        }
        set {
            this.f15_LastXRayDateField = value;
        }
    }
    
    /// <remarks/>
    public string F15_HearingAndVisionPrescriptionDate {
        get {
            return this.f15_HearingAndVisionPrescriptionDateField;
        }
        set {
            this.f15_HearingAndVisionPrescriptionDateField = value;
        }
    }
    
    /// <remarks/>
    public string F15_AssumedCareStartDate {
        get {
            return this.f15_AssumedCareStartDateField;
        }
        set {
            this.f15_AssumedCareStartDateField = value;
        }
    }
    
    /// <remarks/>
    public string F15_AssumedCareEndDate {
        get {
            return this.f15_AssumedCareEndDateField;
        }
        set {
            this.f15_AssumedCareEndDateField = value;
        }
    }
    
    /// <remarks/>
    public string F15_PropertyCasualtyFirstContactDate {
        get {
            return this.f15_PropertyCasualtyFirstContactDateField;
        }
        set {
            this.f15_PropertyCasualtyFirstContactDateField = value;
        }
    }
    
    /// <remarks/>
    public string F16_LastWorkedDate {
        get {
            return this.f16_LastWorkedDateField;
        }
        set {
            this.f16_LastWorkedDateField = value;
        }
    }
    
    /// <remarks/>
    public string F16_AuthorizedReturnToWorkDate {
        get {
            return this.f16_AuthorizedReturnToWorkDateField;
        }
        set {
            this.f16_AuthorizedReturnToWorkDateField = value;
        }
    }
    
    /// <remarks/>
    public string F17_ReferringProviderNameLast {
        get {
            return this.f17_ReferringProviderNameLastField;
        }
        set {
            this.f17_ReferringProviderNameLastField = value;
        }
    }
    
    /// <remarks/>
    public string F17_ReferringProviderNameFirst {
        get {
            return this.f17_ReferringProviderNameFirstField;
        }
        set {
            this.f17_ReferringProviderNameFirstField = value;
        }
    }
    
    /// <remarks/>
    public string F17_ReferringProviderNameMiddle {
        get {
            return this.f17_ReferringProviderNameMiddleField;
        }
        set {
            this.f17_ReferringProviderNameMiddleField = value;
        }
    }
    
    /// <remarks/>
    public string F17_ReferringProviderSuffix {
        get {
            return this.f17_ReferringProviderSuffixField;
        }
        set {
            this.f17_ReferringProviderSuffixField = value;
        }
    }
    
    /// <remarks/>
    public string F17_SupervisingProviderNameLast {
        get {
            return this.f17_SupervisingProviderNameLastField;
        }
        set {
            this.f17_SupervisingProviderNameLastField = value;
        }
    }
    
    /// <remarks/>
    public string F17_SupervisingProviderNameFirst {
        get {
            return this.f17_SupervisingProviderNameFirstField;
        }
        set {
            this.f17_SupervisingProviderNameFirstField = value;
        }
    }
    
    /// <remarks/>
    public string F17_SupervisingProviderNameMiddle {
        get {
            return this.f17_SupervisingProviderNameMiddleField;
        }
        set {
            this.f17_SupervisingProviderNameMiddleField = value;
        }
    }
    
    /// <remarks/>
    public string F17_SupervisingProviderSuffix {
        get {
            return this.f17_SupervisingProviderSuffixField;
        }
        set {
            this.f17_SupervisingProviderSuffixField = value;
        }
    }
    
    /// <remarks/>
    public string F17_OrderingProviderNameLast {
        get {
            return this.f17_OrderingProviderNameLastField;
        }
        set {
            this.f17_OrderingProviderNameLastField = value;
        }
    }
    
    /// <remarks/>
    public string F17_OrderingProviderNameFirst {
        get {
            return this.f17_OrderingProviderNameFirstField;
        }
        set {
            this.f17_OrderingProviderNameFirstField = value;
        }
    }
    
    /// <remarks/>
    public string F17_OrderingProviderNameMiddle {
        get {
            return this.f17_OrderingProviderNameMiddleField;
        }
        set {
            this.f17_OrderingProviderNameMiddleField = value;
        }
    }
    
    /// <remarks/>
    public string F17_OrderingProviderSuffix {
        get {
            return this.f17_OrderingProviderSuffixField;
        }
        set {
            this.f17_OrderingProviderSuffixField = value;
        }
    }
    
    /// <remarks/>
    public string F17A_ReferringProviderIdNumber {
        get {
            return this.f17A_ReferringProviderIdNumberField;
        }
        set {
            this.f17A_ReferringProviderIdNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F17A_SupervisingProviderIdNumber {
        get {
            return this.f17A_SupervisingProviderIdNumberField;
        }
        set {
            this.f17A_SupervisingProviderIdNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F17A_OrderingProviderIdNumber {
        get {
            return this.f17A_OrderingProviderIdNumberField;
        }
        set {
            this.f17A_OrderingProviderIdNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F17B_ReferringProviderNpi {
        get {
            return this.f17B_ReferringProviderNpiField;
        }
        set {
            this.f17B_ReferringProviderNpiField = value;
        }
    }
    
    /// <remarks/>
    public string F17B_SupervisingProviderNpi {
        get {
            return this.f17B_SupervisingProviderNpiField;
        }
        set {
            this.f17B_SupervisingProviderNpiField = value;
        }
    }
    
    /// <remarks/>
    public string F17B_OrderingProviderNpi {
        get {
            return this.f17B_OrderingProviderNpiField;
        }
        set {
            this.f17B_OrderingProviderNpiField = value;
        }
    }
    
    /// <remarks/>
    public string F18_HospitalizationDateFrom {
        get {
            return this.f18_HospitalizationDateFromField;
        }
        set {
            this.f18_HospitalizationDateFromField = value;
        }
    }
    
    /// <remarks/>
    public string F18_HospitalizationDateTo {
        get {
            return this.f18_HospitalizationDateToField;
        }
        set {
            this.f18_HospitalizationDateToField = value;
        }
    }
    
    /// <remarks/>
    public string F19_ClaimSupplementalInfoNoteText {
        get {
            return this.f19_ClaimSupplementalInfoNoteTextField;
        }
        set {
            this.f19_ClaimSupplementalInfoNoteTextField = value;
        }
    }
    
    /// <remarks/>
    public string F21_IcdIndicator {
        get {
            return this.f21_IcdIndicatorField;
        }
        set {
            this.f21_IcdIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public string[] F21_DiagnosisCodes {
        get {
            return this.f21_DiagnosisCodesField;
        }
        set {
            this.f21_DiagnosisCodesField = value;
        }
    }
    
    /// <remarks/>
    public string F22_MedicaidResubmissionCode {
        get {
            return this.f22_MedicaidResubmissionCodeField;
        }
        set {
            this.f22_MedicaidResubmissionCodeField = value;
        }
    }
    
    /// <remarks/>
    public string F22_OriginalReferenceNumber {
        get {
            return this.f22_OriginalReferenceNumberField;
        }
        set {
            this.f22_OriginalReferenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F23_PriorAuthorizationNumber {
        get {
            return this.f23_PriorAuthorizationNumberField;
        }
        set {
            this.f23_PriorAuthorizationNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F23_ReferralNumber {
        get {
            return this.f23_ReferralNumberField;
        }
        set {
            this.f23_ReferralNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F23_ClinicalLaboratoryImprovementAmendmentNumber {
        get {
            return this.f23_ClinicalLaboratoryImprovementAmendmentNumberField;
        }
        set {
            this.f23_ClinicalLaboratoryImprovementAmendmentNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F23_MammographyCertificationNumber {
        get {
            return this.f23_MammographyCertificationNumberField;
        }
        set {
            this.f23_MammographyCertificationNumberField = value;
        }
    }
    
    /// <remarks/>
    public F24ClaimLines[] F24_ClaimLines {
        get {
            return this.f24_ClaimLinesField;
        }
        set {
            this.f24_ClaimLinesField = value;
        }
    }
    
    /// <remarks/>
    public string F25_FederalTaxIdEin {
        get {
            return this.f25_FederalTaxIdEinField;
        }
        set {
            this.f25_FederalTaxIdEinField = value;
        }
    }
    
    /// <remarks/>
    public string F25_FederalTaxIdSsn {
        get {
            return this.f25_FederalTaxIdSsnField;
        }
        set {
            this.f25_FederalTaxIdSsnField = value;
        }
    }
    
    /// <remarks/>
    public string F26_PatientAcctNumber {
        get {
            return this.f26_PatientAcctNumberField;
        }
        set {
            this.f26_PatientAcctNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F27_AcceptAssignment {
        get {
            return this.f27_AcceptAssignmentField;
        }
        set {
            this.f27_AcceptAssignmentField = value;
        }
    }
    
    /// <remarks/>
    public decimal F28_TotalCharge {
        get {
            return this.f28_TotalChargeField;
        }
        set {
            this.f28_TotalChargeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> F29_PatientAmountPaid {
        get {
            return this.f29_PatientAmountPaidField;
        }
        set {
            this.f29_PatientAmountPaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> F29_PayerAmountPaid {
        get {
            return this.f29_PayerAmountPaidField;
        }
        set {
            this.f29_PayerAmountPaidField = value;
        }
    }
    
    /// <remarks/>
    public bool F31_PhysicianOrSupplierSignatureIsOnFile {
        get {
            return this.f31_PhysicianOrSupplierSignatureIsOnFileField;
        }
        set {
            this.f31_PhysicianOrSupplierSignatureIsOnFileField = value;
        }
    }
    
    /// <remarks/>
    public string F32_FacilityName {
        get {
            return this.f32_FacilityNameField;
        }
        set {
            this.f32_FacilityNameField = value;
        }
    }
    
    /// <remarks/>
    public string F32_FacilityAddress1 {
        get {
            return this.f32_FacilityAddress1Field;
        }
        set {
            this.f32_FacilityAddress1Field = value;
        }
    }
    
    /// <remarks/>
    public string F32_FacilityAddress2 {
        get {
            return this.f32_FacilityAddress2Field;
        }
        set {
            this.f32_FacilityAddress2Field = value;
        }
    }
    
    /// <remarks/>
    public string F32_FacilityCity {
        get {
            return this.f32_FacilityCityField;
        }
        set {
            this.f32_FacilityCityField = value;
        }
    }
    
    /// <remarks/>
    public string F32_FacilityState {
        get {
            return this.f32_FacilityStateField;
        }
        set {
            this.f32_FacilityStateField = value;
        }
    }
    
    /// <remarks/>
    public string F32_FacilityZip {
        get {
            return this.f32_FacilityZipField;
        }
        set {
            this.f32_FacilityZipField = value;
        }
    }
    
    /// <remarks/>
    public string F32A_FacilityNpi {
        get {
            return this.f32A_FacilityNpiField;
        }
        set {
            this.f32A_FacilityNpiField = value;
        }
    }
    
    /// <remarks/>
    public string F32B_FacilityIdStateLicenseNumber {
        get {
            return this.f32B_FacilityIdStateLicenseNumberField;
        }
        set {
            this.f32B_FacilityIdStateLicenseNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F32B_FacilityIdProviderCommercialLicenseNumber {
        get {
            return this.f32B_FacilityIdProviderCommercialLicenseNumberField;
        }
        set {
            this.f32B_FacilityIdProviderCommercialLicenseNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F32B_FacilityIdLocationNumber {
        get {
            return this.f32B_FacilityIdLocationNumberField;
        }
        set {
            this.f32B_FacilityIdLocationNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderNameLast {
        get {
            return this.f33_BillingProviderNameLastField;
        }
        set {
            this.f33_BillingProviderNameLastField = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderNameFirst {
        get {
            return this.f33_BillingProviderNameFirstField;
        }
        set {
            this.f33_BillingProviderNameFirstField = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderNameMiddle {
        get {
            return this.f33_BillingProviderNameMiddleField;
        }
        set {
            this.f33_BillingProviderNameMiddleField = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderSuffix {
        get {
            return this.f33_BillingProviderSuffixField;
        }
        set {
            this.f33_BillingProviderSuffixField = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderAddress1 {
        get {
            return this.f33_BillingProviderAddress1Field;
        }
        set {
            this.f33_BillingProviderAddress1Field = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderAddress2 {
        get {
            return this.f33_BillingProviderAddress2Field;
        }
        set {
            this.f33_BillingProviderAddress2Field = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderCity {
        get {
            return this.f33_BillingProviderCityField;
        }
        set {
            this.f33_BillingProviderCityField = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderState {
        get {
            return this.f33_BillingProviderStateField;
        }
        set {
            this.f33_BillingProviderStateField = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderZip {
        get {
            return this.f33_BillingProviderZipField;
        }
        set {
            this.f33_BillingProviderZipField = value;
        }
    }
    
    /// <remarks/>
    public string F33_BillingProviderPhoneNumber {
        get {
            return this.f33_BillingProviderPhoneNumberField;
        }
        set {
            this.f33_BillingProviderPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F33A_BillingProviderNpi {
        get {
            return this.f33A_BillingProviderNpiField;
        }
        set {
            this.f33A_BillingProviderNpiField = value;
        }
    }
    
    /// <remarks/>
    public string F33B_BillingProviderTaxonomyCode {
        get {
            return this.f33B_BillingProviderTaxonomyCodeField;
        }
        set {
            this.f33B_BillingProviderTaxonomyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string F33B_BillingProviderEmployersIdentificationNumber {
        get {
            return this.f33B_BillingProviderEmployersIdentificationNumberField;
        }
        set {
            this.f33B_BillingProviderEmployersIdentificationNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F33B_BillingProviderSsn {
        get {
            return this.f33B_BillingProviderSsnField;
        }
        set {
            this.f33B_BillingProviderSsnField = value;
        }
    }
    
    /// <remarks/>
    public string X12_PlaceOfServiceCode {
        get {
            return this.x12_PlaceOfServiceCodeField;
        }
        set {
            this.x12_PlaceOfServiceCodeField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RendProviderNameLast {
        get {
            return this.x12_RendProviderNameLastField;
        }
        set {
            this.x12_RendProviderNameLastField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RendProviderNameFirst {
        get {
            return this.x12_RendProviderNameFirstField;
        }
        set {
            this.x12_RendProviderNameFirstField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RendProviderNameMiddle {
        get {
            return this.x12_RendProviderNameMiddleField;
        }
        set {
            this.x12_RendProviderNameMiddleField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RendProviderSuffix {
        get {
            return this.x12_RendProviderSuffixField;
        }
        set {
            this.x12_RendProviderSuffixField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RendProviderTaxonomyCode {
        get {
            return this.x12_RendProviderTaxonomyCodeField;
        }
        set {
            this.x12_RendProviderTaxonomyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RendProviderStateLicenseNumber {
        get {
            return this.x12_RendProviderStateLicenseNumberField;
        }
        set {
            this.x12_RendProviderStateLicenseNumberField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RendProviderUpinNumber {
        get {
            return this.x12_RendProviderUpinNumberField;
        }
        set {
            this.x12_RendProviderUpinNumberField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RendProviderCommercialNumber {
        get {
            return this.x12_RendProviderCommercialNumberField;
        }
        set {
            this.x12_RendProviderCommercialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RendProviderLocationNumber {
        get {
            return this.x12_RendProviderLocationNumberField;
        }
        set {
            this.x12_RendProviderLocationNumberField = value;
        }
    }
    
    /// <remarks/>
    public string X12_RenderingNPI {
        get {
            return this.x12_RenderingNPIField;
        }
        set {
            this.x12_RenderingNPIField = value;
        }
    }
    
    /// <remarks/>
    public string X12_AcuteManifestationCode {
        get {
            return this.x12_AcuteManifestationCodeField;
        }
        set {
            this.x12_AcuteManifestationCodeField = value;
        }
    }
    
    /// <remarks/>
    public string X12_ClaimAdjudicationDate {
        get {
            return this.x12_ClaimAdjudicationDateField;
        }
        set {
            this.x12_ClaimAdjudicationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> X12_ClaimPrimaryPayerPaidAmount {
        get {
            return this.x12_ClaimPrimaryPayerPaidAmountField;
        }
        set {
            this.x12_ClaimPrimaryPayerPaidAmountField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_ClaimContractualObligationAdjustments {
        get {
            return this.x12_ClaimContractualObligationAdjustmentsField;
        }
        set {
            this.x12_ClaimContractualObligationAdjustmentsField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_ClaimCorrectionAndReversalAdjustments {
        get {
            return this.x12_ClaimCorrectionAndReversalAdjustmentsField;
        }
        set {
            this.x12_ClaimCorrectionAndReversalAdjustmentsField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_ClaimOtherAdjustments {
        get {
            return this.x12_ClaimOtherAdjustmentsField;
        }
        set {
            this.x12_ClaimOtherAdjustmentsField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_ClaimPayorInitiatedReductions {
        get {
            return this.x12_ClaimPayorInitiatedReductionsField;
        }
        set {
            this.x12_ClaimPayorInitiatedReductionsField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_ClaimPatientResponsibilityAdjustments {
        get {
            return this.x12_ClaimPatientResponsibilityAdjustmentsField;
        }
        set {
            this.x12_ClaimPatientResponsibilityAdjustmentsField = value;
        }
    }
    
    /// <remarks/>
    public string X12_MedicalRecordNumber {
        get {
            return this.x12_MedicalRecordNumberField;
        }
        set {
            this.x12_MedicalRecordNumberField = value;
        }
    }
    
    /// <remarks/>
    public PatientConditionInfo[] X12_SpectacleLenses {
        get {
            return this.x12_SpectacleLensesField;
        }
        set {
            this.x12_SpectacleLensesField = value;
        }
    }
    
    /// <remarks/>
    public PatientConditionInfo[] X12_ContactLenses {
        get {
            return this.x12_ContactLensesField;
        }
        set {
            this.x12_ContactLensesField = value;
        }
    }
    
    /// <remarks/>
    public PatientConditionInfo[] X12_SpectacleFrames {
        get {
            return this.x12_SpectacleFramesField;
        }
        set {
            this.x12_SpectacleFramesField = value;
        }
    }
    
    /// <remarks/>
    public string X12_DisabilityDateFrom {
        get {
            return this.x12_DisabilityDateFromField;
        }
        set {
            this.x12_DisabilityDateFromField = value;
        }
    }
    
    /// <remarks/>
    public string X12_DisabilityDateTo {
        get {
            return this.x12_DisabilityDateToField;
        }
        set {
            this.x12_DisabilityDateToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> X12_ClaimContractMonetaryAmount {
        get {
            return this.x12_ClaimContractMonetaryAmountField;
        }
        set {
            this.x12_ClaimContractMonetaryAmountField = value;
        }
    }
    
    /// <remarks/>
    public string X12_ClaimContractTypeCode {
        get {
            return this.x12_ClaimContractTypeCodeField;
        }
        set {
            this.x12_ClaimContractTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    public string X12_ClaimContractCode {
        get {
            return this.x12_ClaimContractCodeField;
        }
        set {
            this.x12_ClaimContractCodeField = value;
        }
    }
    
    /// <remarks/>
    public string X12_DelayReasonCode {
        get {
            return this.x12_DelayReasonCodeField;
        }
        set {
            this.x12_DelayReasonCodeField = value;
        }
    }
    
    /// <remarks/>
    public string X12_OtherPayerName {
        get {
            return this.x12_OtherPayerNameField;
        }
        set {
            this.x12_OtherPayerNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class F24ClaimLines {
    
    private string f24A_DateOfServiceFromField;
    
    private string f24A_DateOfServiceToField;
    
    private string f24B_PlaceOfServiceCodeField;
    
    private bool f24C_EmgField;
    
    private string f24D_HcpcsProcedureCodeField;
    
    private string[] f24D_ModifiersField;
    
    private string x12_DescriptionField;
    
    private string[] f24E_DiagnosisPointersField;
    
    private System.Nullable<decimal> f24F_ChargesField;
    
    private System.Nullable<decimal> f24G_DaysOrUnitsField;
    
    private bool f24H_EarlyPeriodicScreeningDiagnosisAndTreatmentField;
    
    private bool f24H_FamilyPlannningField;
    
    private string f24J_Shaded_RendProviderTaxonomyCodeField;
    
    private string f24J_Shaded_RendProviderStateLicenseNumberField;
    
    private string f24J_Shaded_RendProviderUpinNumberField;
    
    private string f24J_Shaded_RendProviderCommercialNumberField;
    
    private string f24J_Shaded_RendProviderLocationNumberField;
    
    private string f24J_RenderingNpiField;
    
    private bool x12_AnesthesiaField;
    
    private System.Nullable<decimal> x12_ContractMonetaryAmountField;
    
    private string x12_ContractTypeCodeField;
    
    private string x12_AdjudicationOrPaymentDateField;
    
    private ClaimsAdjustment[] x12_LineContractualObligationAdjustmentsField;
    
    private ClaimsAdjustment[] x12_LineCorrectionAndReversalAdjustmentsField;
    
    private ClaimsAdjustment[] x12_LineOtherAdjustmentsField;
    
    private ClaimsAdjustment[] x12_LinePayorInitiatedReductionsField;
    
    private ClaimsAdjustment[] x12_LinePatientResponsibilityAdjustmentsField;
    
    private string x12_MeasurementIdField;
    
    private string x12_MeasurementQualifierField;
    
    private decimal x12_MeasurementValueField;
    
    private string x12_NdcCodeField;
    
    private decimal x12_NdcQuantityField;
    
    private string x12_DrugQuantityInternationalUnitsField;
    
    private string x12_DrugQuantityGramsField;
    
    private string x12_DrugQuantityMilligramsField;
    
    private string x12_DrugQuantityMillilitersField;
    
    private string x12_DrugQuantityUnitsField;
    
    private string x12_NdcPharmacyPrescriptionNumberField;
    
    private string x12_NdcLinkSequenceNumberField;
    
    private System.Nullable<decimal> x12_PrimaryPayerPaidAmountField;
    
    private string x12_ProviderControlNumberField;
    
    private string f24_Shaded_LineNoteTextField;
    
    /// <remarks/>
    public string F24A_DateOfServiceFrom {
        get {
            return this.f24A_DateOfServiceFromField;
        }
        set {
            this.f24A_DateOfServiceFromField = value;
        }
    }
    
    /// <remarks/>
    public string F24A_DateOfServiceTo {
        get {
            return this.f24A_DateOfServiceToField;
        }
        set {
            this.f24A_DateOfServiceToField = value;
        }
    }
    
    /// <remarks/>
    public string F24B_PlaceOfServiceCode {
        get {
            return this.f24B_PlaceOfServiceCodeField;
        }
        set {
            this.f24B_PlaceOfServiceCodeField = value;
        }
    }
    
    /// <remarks/>
    public bool F24C_Emg {
        get {
            return this.f24C_EmgField;
        }
        set {
            this.f24C_EmgField = value;
        }
    }
    
    /// <remarks/>
    public string F24D_HcpcsProcedureCode {
        get {
            return this.f24D_HcpcsProcedureCodeField;
        }
        set {
            this.f24D_HcpcsProcedureCodeField = value;
        }
    }
    
    /// <remarks/>
    public string[] F24D_Modifiers {
        get {
            return this.f24D_ModifiersField;
        }
        set {
            this.f24D_ModifiersField = value;
        }
    }
    
    /// <remarks/>
    public string X12_Description {
        get {
            return this.x12_DescriptionField;
        }
        set {
            this.x12_DescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string[] F24E_DiagnosisPointers {
        get {
            return this.f24E_DiagnosisPointersField;
        }
        set {
            this.f24E_DiagnosisPointersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> F24F_Charges {
        get {
            return this.f24F_ChargesField;
        }
        set {
            this.f24F_ChargesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> F24G_DaysOrUnits {
        get {
            return this.f24G_DaysOrUnitsField;
        }
        set {
            this.f24G_DaysOrUnitsField = value;
        }
    }
    
    /// <remarks/>
    public bool F24H_EarlyPeriodicScreeningDiagnosisAndTreatment {
        get {
            return this.f24H_EarlyPeriodicScreeningDiagnosisAndTreatmentField;
        }
        set {
            this.f24H_EarlyPeriodicScreeningDiagnosisAndTreatmentField = value;
        }
    }
    
    /// <remarks/>
    public bool F24H_FamilyPlannning {
        get {
            return this.f24H_FamilyPlannningField;
        }
        set {
            this.f24H_FamilyPlannningField = value;
        }
    }
    
    /// <remarks/>
    public string F24J_Shaded_RendProviderTaxonomyCode {
        get {
            return this.f24J_Shaded_RendProviderTaxonomyCodeField;
        }
        set {
            this.f24J_Shaded_RendProviderTaxonomyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string F24J_Shaded_RendProviderStateLicenseNumber {
        get {
            return this.f24J_Shaded_RendProviderStateLicenseNumberField;
        }
        set {
            this.f24J_Shaded_RendProviderStateLicenseNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F24J_Shaded_RendProviderUpinNumber {
        get {
            return this.f24J_Shaded_RendProviderUpinNumberField;
        }
        set {
            this.f24J_Shaded_RendProviderUpinNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F24J_Shaded_RendProviderCommercialNumber {
        get {
            return this.f24J_Shaded_RendProviderCommercialNumberField;
        }
        set {
            this.f24J_Shaded_RendProviderCommercialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F24J_Shaded_RendProviderLocationNumber {
        get {
            return this.f24J_Shaded_RendProviderLocationNumberField;
        }
        set {
            this.f24J_Shaded_RendProviderLocationNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F24J_RenderingNpi {
        get {
            return this.f24J_RenderingNpiField;
        }
        set {
            this.f24J_RenderingNpiField = value;
        }
    }
    
    /// <remarks/>
    public bool X12_Anesthesia {
        get {
            return this.x12_AnesthesiaField;
        }
        set {
            this.x12_AnesthesiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> X12_ContractMonetaryAmount {
        get {
            return this.x12_ContractMonetaryAmountField;
        }
        set {
            this.x12_ContractMonetaryAmountField = value;
        }
    }
    
    /// <remarks/>
    public string X12_ContractTypeCode {
        get {
            return this.x12_ContractTypeCodeField;
        }
        set {
            this.x12_ContractTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    public string X12_AdjudicationOrPaymentDate {
        get {
            return this.x12_AdjudicationOrPaymentDateField;
        }
        set {
            this.x12_AdjudicationOrPaymentDateField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_LineContractualObligationAdjustments {
        get {
            return this.x12_LineContractualObligationAdjustmentsField;
        }
        set {
            this.x12_LineContractualObligationAdjustmentsField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_LineCorrectionAndReversalAdjustments {
        get {
            return this.x12_LineCorrectionAndReversalAdjustmentsField;
        }
        set {
            this.x12_LineCorrectionAndReversalAdjustmentsField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_LineOtherAdjustments {
        get {
            return this.x12_LineOtherAdjustmentsField;
        }
        set {
            this.x12_LineOtherAdjustmentsField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_LinePayorInitiatedReductions {
        get {
            return this.x12_LinePayorInitiatedReductionsField;
        }
        set {
            this.x12_LinePayorInitiatedReductionsField = value;
        }
    }
    
    /// <remarks/>
    public ClaimsAdjustment[] X12_LinePatientResponsibilityAdjustments {
        get {
            return this.x12_LinePatientResponsibilityAdjustmentsField;
        }
        set {
            this.x12_LinePatientResponsibilityAdjustmentsField = value;
        }
    }
    
    /// <remarks/>
    public string X12_MeasurementId {
        get {
            return this.x12_MeasurementIdField;
        }
        set {
            this.x12_MeasurementIdField = value;
        }
    }
    
    /// <remarks/>
    public string X12_MeasurementQualifier {
        get {
            return this.x12_MeasurementQualifierField;
        }
        set {
            this.x12_MeasurementQualifierField = value;
        }
    }
    
    /// <remarks/>
    public decimal X12_MeasurementValue {
        get {
            return this.x12_MeasurementValueField;
        }
        set {
            this.x12_MeasurementValueField = value;
        }
    }
    
    /// <remarks/>
    public string X12_NdcCode {
        get {
            return this.x12_NdcCodeField;
        }
        set {
            this.x12_NdcCodeField = value;
        }
    }
    
    /// <remarks/>
    public decimal X12_NdcQuantity {
        get {
            return this.x12_NdcQuantityField;
        }
        set {
            this.x12_NdcQuantityField = value;
        }
    }
    
    /// <remarks/>
    public string X12_DrugQuantityInternationalUnits {
        get {
            return this.x12_DrugQuantityInternationalUnitsField;
        }
        set {
            this.x12_DrugQuantityInternationalUnitsField = value;
        }
    }
    
    /// <remarks/>
    public string X12_DrugQuantityGrams {
        get {
            return this.x12_DrugQuantityGramsField;
        }
        set {
            this.x12_DrugQuantityGramsField = value;
        }
    }
    
    /// <remarks/>
    public string X12_DrugQuantityMilligrams {
        get {
            return this.x12_DrugQuantityMilligramsField;
        }
        set {
            this.x12_DrugQuantityMilligramsField = value;
        }
    }
    
    /// <remarks/>
    public string X12_DrugQuantityMilliliters {
        get {
            return this.x12_DrugQuantityMillilitersField;
        }
        set {
            this.x12_DrugQuantityMillilitersField = value;
        }
    }
    
    /// <remarks/>
    public string X12_DrugQuantityUnits {
        get {
            return this.x12_DrugQuantityUnitsField;
        }
        set {
            this.x12_DrugQuantityUnitsField = value;
        }
    }
    
    /// <remarks/>
    public string X12_NdcPharmacyPrescriptionNumber {
        get {
            return this.x12_NdcPharmacyPrescriptionNumberField;
        }
        set {
            this.x12_NdcPharmacyPrescriptionNumberField = value;
        }
    }
    
    /// <remarks/>
    public string X12_NdcLinkSequenceNumber {
        get {
            return this.x12_NdcLinkSequenceNumberField;
        }
        set {
            this.x12_NdcLinkSequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> X12_PrimaryPayerPaidAmount {
        get {
            return this.x12_PrimaryPayerPaidAmountField;
        }
        set {
            this.x12_PrimaryPayerPaidAmountField = value;
        }
    }
    
    /// <remarks/>
    public string X12_ProviderControlNumber {
        get {
            return this.x12_ProviderControlNumberField;
        }
        set {
            this.x12_ProviderControlNumberField = value;
        }
    }
    
    /// <remarks/>
    public string F24_Shaded_LineNoteText {
        get {
            return this.f24_Shaded_LineNoteTextField;
        }
        set {
            this.f24_Shaded_LineNoteTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ClaimsAdjustment {
    
    private string reasonCodeField;
    
    private decimal amountField;
    
    private decimal quantityField;
    
    /// <remarks/>
    public string ReasonCode {
        get {
            return this.reasonCodeField;
        }
        set {
            this.reasonCodeField = value;
        }
    }
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public decimal Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PatientConditionInfo {
    
    private bool certificationConditionIndicatorField;
    
    private string[] conditionCodeField;
    
    /// <remarks/>
    public bool CertificationConditionIndicator {
        get {
            return this.certificationConditionIndicatorField;
        }
        set {
            this.certificationConditionIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public string[] ConditionCode {
        get {
            return this.conditionCodeField;
        }
        set {
            this.conditionCodeField = value;
        }
    }
}
